# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P92JCsv9yh-TtFmFDAZcWZ_mpHVmwHjX

# Week-3

### Which of the following demonstrates how regex (regular expressions) might be used?


* Recognize an image


* Calculate Pi

* Multiply and divide arrays

* **Find strings of text that match a pattern**

( Correct. Awesome! Regex is a search query that matches the regular expression pattern you've specified. )

### Rather than using the index() function of the string module, we can use regular expressions, which are more flexible. After importing the regular expression module re, what regex function might be used instead of standard methods?

* re.pid()


* re.index()


* re.regex()

* **re.search()**

( Correct.
Great job! Using the re module provides more robust solutions, not limited to just re.search(). )

### Using the terminal, which of the following commands will correctly use grep to find the words “sling” and “sting” (assuming they are in our file, file.txt)?

* user@ubuntu:~$ grep sting+sling /usr/file.txt

* user@ubuntu:~$ grep(s.ing) /usr/file.txt

* user@ubuntu:~$ grep s+ing /usr/file.txt

* **user@ubuntu:~$ grep s.ing /usr/file.txt**

( Correct.
Nice work! In regex, a dot is a wildcard, so it can represent any character. This command will print both “sting” and “sling”, if they are in the file. )
"""

# Fill in the code to check if the text passed contains the vowels a, e and i, 
# with exactly one occurrence of any other character in between.

import re
def check_aei (text):
  result = re.search(r"a.e.i", text)
  return result != None

print(check_aei("academia")) # True
print(check_aei("aerial")) # False
print(check_aei("paramedic")) # True

# Fill in the code to check if the text passed contains punctuation symbols: 
# commas, periods, colons, semicolons, question marks, and exclamation points.

import re
def check_punctuation (text):
  result = re.search(r"[,.:;?!]", text)
  return result != None

print(check_punctuation("This is a sentence that ends with a period.")) # True
print(check_punctuation("This is a sentence fragment without a period")) # False
print(check_punctuation("Aren't regular expressions awesome?")) # True
print(check_punctuation("Wow! We're really picking up some steam now!")) # True
print(check_punctuation("End of the line")) # False